### ISSUE TITLE
Would it be possible to change the license to more permissive one?

### ISSUE THREAD

**Issue by hajimehoshi** [aguegu/BitmapFont#2]
Hi,

Thank you for your great work!

I considered to use this font glyphs for our games and/or libraries, but one concern is license. GPL3 means that our games must be open and licensed under GPL3.

I was wondering if it would be possible to change the license to a more permissive license like MIT or SIL Font License.

Thanks,

**Comment by hajimehoshi** [comment]
I assumed you had the copyright for the data (ASC* and HZK*), but perhaps isn't it true?

**Comment by aguegu** [comment]
No, I do not have copyright for the fonts.
