### ISSUE TITLE
您好，原始博客页面地址失效了

### ISSUE THREAD

**Issue by TakWolf** [aguegu/BitmapFont#3]
就是关于介绍这个项目的博文。
原始地址为：http://aguegu.net/?p=1279  
目前访问提示：建立数据库连接时出错

看到您好像搭建了新的博客地址。会恢复这篇文章吗？

我目前在其他项目中使用了该项目字模，希望能将这篇文章地址作为引用参考，用于注明字模的出处来源以及实现原理。

如果您愿意恢复这篇文章就太好了，万分感谢！

**Comment by TakWolf** [comment]
引用的部分在这里：

https://github.com/TakWolf/hzk-pixel-font#%E5%AD%97%E4%BD%93

**Comment by aguegu** [comment]
我也希望恢复哈，但是目前没有什么办法呢，运营方已经找不到了。

**Comment by TakWolf** [comment]
http://web.archive.org/web/20161108093925/http://aguegu.net/?p=1279

找到了 2016 年的存档，暂时会改成引用这个

感谢博主的分享，希望你能顺利修复数据

**Comment by aguegu** [comment]
有心了，谢谢
